import { useEffect, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { cn } from "@/lib/utils";
export function Confetti({ active = true }: { active?: boolean }) {
 const pieces=useMemo(()=>Array.from({length:70},(_,i)=>({x:(i*47)%100,delay:(i%12)*.035,rotate:(i*73)%360,drift:(i*31)%80-40})),[]);
 if(!active)return null; return <div className="pointer-events-none fixed inset-0 z-50 overflow-hidden" aria-hidden>{pieces.map((p,i)=><motion.span key={i} initial={{y:-30,x:`${p.x}vw`,opacity:0}} animate={{y:"110vh",x:`calc(${p.x}vw + ${p.drift}px)`,opacity:[0,1,1,0],rotate:p.rotate+540}} transition={{duration:2.8+(i%5)*.25,delay:p.delay,ease:"easeOut"}} className={cn("absolute top-0 h-3 w-2 rounded-sm",["bg-primary","bg-secondary","bg-accent","bg-ans-2","bg-ans-3"][i%5])}/>)}</div>;
}
export function GameBurst({type}:{type:"correct"|"wrong"|"win"|null}) { const text=type==="correct"?"⚡ PERFECT!":type==="wrong"?"💥 OOPS!":type==="win"?"🏆 GREAT RUN!":""; return <AnimatePresence>{type&&<motion.div initial={{opacity:0,scale:.5,y:30}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0,scale:1.4}} className="pointer-events-none fixed inset-x-0 top-1/3 z-40 flex justify-center"><div className="rounded-[2rem] border border-white/15 bg-background/85 px-8 py-5 font-display text-4xl shadow-2xl backdrop-blur-xl sm:text-6xl">{text}</div></motion.div>}</AnimatePresence>; }
export function useGameSound(enabled=true){useEffect(()=>{},[enabled]); return (kind:"tick"|"select"|"correct"|"wrong"|"win")=>{if(!enabled||typeof window==="undefined")return;try{const Ctx=window.AudioContext||(window as typeof window & {webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!Ctx)return;const ctx=new Ctx();const osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value={tick:520,select:660,correct:880,wrong:180,win:1040}[kind];osc.type=kind==="wrong"?"sawtooth":"sine";gain.gain.setValueAtTime(.0001,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(kind==="win"?.16:.08,ctx.currentTime+.01);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+(kind==="win"?.45:.16));osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.5);}catch{}};}
